name: Build Sample App for CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '10.0.x'

jobs:
  build-sample-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Install .NET MAUI workload
        run: dotnet workload install maui-android
      - name: Restore
        run: dotnet restore samples/Plugin.Maui.Rotatable.Sample/Plugin.Maui.Rotatable.Sample.csproj -p:TargetFramework=net10.0-android
      - name: Build
        run: dotnet build samples/Plugin.Maui.Rotatable.Sample/Plugin.Maui.Rotatable.Sample.csproj -f net10.0-android -c Release --no-restore --no-incremental
